# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3171de9ea9934a7fc4cd4ba37e353ea9c6905b9a7570a612ad04560d4e3d7cdf0c014f7d832d596cbcce7df5f5ca9eb23e0f1562adb0d3c91f7f1c99b10285b

test:
  secret_key_base: 55c5fbb29597e7bde3dfd464b75de85450a32fd842fff8804e6520b2a17cfb6014209e2d35b38c0e538bf67c407c5985286ff4a5132599f0457e6cca0817d992

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
